{
  "stages": [
    "build"
  ],
  "workflow": {
    "rules": [
      {
        "if": '$CI_COMMIT_BRANCH == "master"',
        "when": "always"
      },
      {
        "when": "never"
      }
    ]
  },
  "variables": {
    "NIX_CONFIG": "experimental-features = nix-command flakes\naccept-flake-config = true"
  },
  "build:flake": {
    "stage": "build",
    "image": "nixos/nix:2.32.8",
    "before_script": [
      "nix profile add nixpkgs#cachix",
      "export PATH=$HOME/.nix-profile/bin:$PATH",
      "cachix authtoken $CACHIX_AUTH_TOKEN"
    ],
    "script": [
      "cachix watch-exec sachahjkl -- nix build .#default .#linuxBinary .#dockerImage --no-link"
    ]
  }
}
