ADMIN_PASSWORD_HASH: ENC[AES256_GCM,data:GlLosfUF7oMGVeHrGTi0SqN1lARSgkEZd+hVCIB1bypVccBr2QppjZ33vSa0l/HH/5WZTc59,iv:PajUGZSY5ohpvfXgdUCQWID3DUgs8izopET+hKAuiEM=,tag:60ikHpADDphJsMntGGecQw==,type:str]
ADMIN_PASSWORD_PEPPER: ENC[AES256_GCM,data:uYJez+h942a1UbmvrHmcJrVJoPwtbH4=,iv:UOF1ZX5e0ozSR18887vkIgK9lbBK0MRo9N+6CtZGN48=,tag:+7Z2JaDKo8oK371RyvNJfw==,type:str]
GITHUB_BEARER_TOKEN: ENC[AES256_GCM,data:xH/Ivs1UOIQAt2eyVIPUwhybESR5bUCpcITT+RHx/H9CmVStKdzenKgsPuqkk/O2lchH6VU9gCS134lZH+Uk4zcBYGHYGPm8GxgUGz3PiIfTUHQy983t1R9+wohV,iv:N/L623VL+p48WBUz54E8D00Dq9GPoAHz4aCKyWENO+c=,tag:fsoQKexqqxEdmK+t+Myong==,type:str]
GITLAB_BEARER_TOKEN: ENC[AES256_GCM,data:pnAKfqQSiNke8ywCgCi7KjYvTerhk9g0zxwuieYhfGRm1NAMBWGXEpJ0RonLHPkOoOw2YRaFhEvs,iv:S2395bc1aNeu7IbK7U4/pvRujGUylqOahapzU2hJip4=,tag:GALz0XvTIG6dNdOzZBI6Yw==,type:str]
PASTE_SECRETS_FILE: ENC[AES256_GCM,data:byV1A6OmdpK4r/KcJrlqz5M03P05DY8TXKWib66L7LJ+kid3zvwJf+azhuLf3uiMLv/T0vXXnrjXo+kznRssq8xKQTDulXDv1TceeZjayK3mkquOVbI9T7cGji63hhZE0BAY1/Bf8jJsB85lSri1fAu/hOJPWrWV4nHgUEQYZpMWZ50fAasx9OjKnz5HySIKHbVmx+iYTgFXH+5AIY2pksx9OXdK3C82QaSjZgcs2xNNsfeD8qjo6BB+DQsRUkkeS4bS+bDL9e/lCIxdk7jnlYQuH2llkj9BJeiH9fy7dCE1736s+sGKxZnOnErJjp4a4VwQoBg24pvcOebHIVytoPSHto/RhHAQjDkRg9TDjCK+F37NE/YKDtOKHkzszvsvfA==,iv:f1e4p79RkY9o8sKkUeatQNWdBnUYU7EI/mCqk08xLKM=,tag:8QUi/aC9RBrZMkeW8aAljw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoV0UxT3d1UC9xYkdWd0xi
            c2FTTFBsVUNPWUNFUlhFaE1GdzNWVEpZaER3Cmx3bEpWZWZNN3NmSVdhSU0waVdN
            bmNxVlNXSjFXNjN4WTFrcVFjb1BEY3MKLS0tIFhQYWdNWXQyRkhUeWR6OG9DUHFr
            ZEpnYnVONExoUUVqRURBeVZvVDVOVVUKEUSHbV69IxuRS3RadyB/Fv9hf0LZCFKF
            JNaJb6mXh79pG2rRudoonIiP+bgk0wM2TgPjO09Npo0/jNKDGeCtxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1t6n6jyy0uwh6px3tl65pjrd5m0f79dv5xja2dcpq2gpvq0jcsyjs6j40fe
    lastmodified: "2026-08-07T14:47:40Z"
    mac: ENC[AES256_GCM,data:YaFHPWI2m2PXeWQDEUFZuSI8w2m+nEGw+VBmCTXIpVMeKyj0M2zkUlb+Tz/UTeplQO2BuKcwAVIjpfeVi6JyK9oyq6Os2DbzprY2xm99l5PeY+tJyso2jI+heK3Y7T2NEmC8JR6o5EdWPfULbR+4TVWxWzmVdEHww34uGJkRuGQ=,iv:uE9bPIeMGHr9IkA9riTiJ0xN1zPFHMQehufSC1y1otQ=,tag:Mz2AvZH2PfRWBI7dvkw/Tw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
