[sacha-house-teapot]
enabled = true
port = http,https
filter = sacha-house-teapot
logpath = /var/log/npm-nginx/proxy-host-*_access.log
maxretry = 10
findtime = 300
bantime = 3600
action = iptables-multiport[name=teapot, port="http,https", protocol=tcp]

